fix: order cors

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -35,7 +35,21 @@ jobs:
           key: ${{ secrets.KEY }}
           script: |
             cd ${{ vars.PROJECT_PATH }}
-            make deploy
+            for i in 1 2 3; do
+              echo "🚀 Deploy attempt $i..."
+
+              make deploy && break
+
+              echo "❌ Attempt $i failed"
+              
+              if [ $i -eq 3 ]; then
+                echo "💥 All attempts failed"
+                exit 1
+              fi
+
+              echo "⏳ Retrying in 5s..."
+              sleep 5
+            done
 
       - name: Notify Telegram Success
         if: success()
